// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "NotIM",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "NotIM",
            targets: ["AppModule"],
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .faceID(purposeString: "Please allow using Face ID to lock your note.")
            ],
            appCategory: .lifestyle
        )
    ],
    dependencies: [
        .package(url: "https://github.com/duraidabdul/LocalConsole", "1.0.0"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "LocalConsole", package: "localconsole")
            ],
            path: "."
        )
    ]
)